{% set name = "verumverify" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 67375b6588ce28bd54346d7bfceaba4cd7dfbf035751b5f29fe603f066dba22b

build:
  number: 0
  entry_points:
    - verify = verumverify.main:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python>=3.6
  run:
    - python>=3.6

test:
  imports:
    - verumverify
  commands:
    - verify --help

about:
  home: "https://github.com/Ethosym/verumverify"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Verifies the authenticity of content published on the Verum Journo portal."
  doc_url: https://github.com/Ethosym/verumverify
  dev_url: https://github.com/Ethosym/verumverify

extra:
  recipe-maintainers:
    - cgdeboer
